export const FETCH_SINGLE_NEWS_REQUEST = 'FETCH_SINGLE_NEWS_REQUEST';
export const FETCH_SINGLE_NEWS_RESPONSE = 'FETCH_SINGLE_NEWS_RESPONSE';
export const FETCH_SINGLE_NEWS_FAILED = 'FETCH_SINGLE_NEWS_FAILED';
